language: csharp
solution: DevTree.BeKurdi.sln
mono: none
dotnet: 1.1.0
dist: trusty

script:
 - dotnet restore
 - dotnet build -c Release
 - dotnet test ./tests/DevTree.BeKurdi.Tests/DevTree.BeKurdi.Tests.csproj
 
deploy:
 skip_cleanup: true
 script:
  - dotnet nuget push ./src/DevTree.BeKurdi/bin/Release/*.nupkg -s ${NUGET_SOURCE} -k ${NUGET_API_KEY}
 on:
   branch: master