language: csharp
solution: DevTree.BeKurdi.sln
mono: none
dotnet: 2.0.0
dist: trusty
branches:
  only:
  - master

script:
 - dotnet restore
 - dotnet build -c Release
 - dotnet nuget push ./src/DevTree.BeKurdi/bin/Release/*.nupkg -s ${NUGET_SOURCE} -k ${NUGET_API_KEY}